main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('class/class_list/', views.class_list, name='class_list'),
    path('class/class_list_all/', views.class_list_all, name='class_list_all'),
    path('class/class_create/', views.class_create, name='class_create'),
    path('class/class_delete/<int:class_code>', views.class_delete, name='class_delete'),
    path('class/class_attend/', views.class_attend, name='class_attend'),
    path('class/post_list/<int:class_code>', views.post_list, name='post_list'),
    path('<int:classroom_id>/', views.detail, name='detail'),
    path('comment/create/<int:classroom_id>/', views.comment_create, name='comment_create'),
    path('classroom/create/<int:class_code>', views.classroom_create, name='classroom_create'),
    path('classroom/modify/<int:classroom_id>/', views.classroom_modify, name='classroom_modify'),
    path('classroom/delete/<int:classroom_id>/', views.classroom_delete, name='classroom_delete'),
    path('comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path('upload/', views.upload, name='upload'),
]

security-education-web/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.index, name='index'), # '/'에 해당하는 path
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Classes(models.Model):
    educator = models.ForeignKey(User, on_delete=models.CASCADE)
    class_name = models.CharField(max_length=200)
    max_learner = models.IntegerField(default=0)
    learners = models.CharField(max_length=300, null=True, blank=True)
    learners_num = models.IntegerField(default=0)
    code = models.IntegerField(default=0)
    create_date = models.DateTimeField(null=True)

class ClassRoom(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    container_cnt = models.CharField(max_length=10)
    docker_image = models.CharField(max_length=100)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    links = models.CharField(max_length=300, null=True, blank=True)
    class_code = models.IntegerField(default=0)

    def __str__(self):
        return self.subject

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    classroom = models.ForeignKey(ClassRoom, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

main/forms.py
from django import forms
from main.models import ClassRoom, Comment, Classes

class ClassRoomForm(forms.ModelForm):
    class Meta:
        model = ClassRoom
        fields = ['subject', 'content', 'docker_image', 'links']

        labels = {
            'subject': '제목',
            'content': '내용',
            'docker_image': '이미지',
            'links': '컨테이너링크',
        }

class ClassesForm(forms.ModelForm):
    class Meta:
        model = Classes
        fields = ['class_name', 'max_learner', 'learners', 'code']

        labels = {
            'class_name': '수업 이름',
            'max_learner': '최대 학생수',
            'learners': '학생 명단',
            'code': '수업 코드',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

main/views.py
import os
from collections import deque

from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import ClassRoom, Comment, Classes
from .forms import ClassRoomForm, CommentForm, ClassesForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.core.files.storage import FileSystemStorage

# educator 접근 권한
def educator_group_check(user):
    for _ in user.groups.all():
        if _.name == 'educator':
            print("Hello, educator")
            return True
    return False

def images():
    result = os.popen('docker images').read().strip().split('\n')

    image_list = []

    for _ in range(1, len(result)):
        print(result[_])
        result_split = result[_].split()
        image_list.append(result_split[0])

    print(image_list)

    return image_list

@user_passes_test(educator_group_check, login_url='/main')
def upload(request):
    abs_path = os.getcwd().split(os.path.sep)
    media_path = '/'
    for _ in range(1, len(abs_path)):
        media_path += abs_path[_]
        media_path += '/'
    media_path += 'media/'

    image_list = os.listdir(media_path)
    result = ''
    if request.method == 'POST' and 'myfile' in request.FILES:
        myfile = request.FILES['myfile']
        if str(myfile) in image_list:
            result = str(myfile) + 'is already exist in media'
            return render(request, 'main/already.html', {'result': result})

        fs = FileSystemStorage(location='media/', base_url='media/')
        # FileSystemStorage.save(file_name, file_content)
        filename = fs.save(myfile.name, myfile)

        result = os.popen('docker load -i '+media_path+filename).read().strip().split('\n')
        result = result[0].split()

        send = ''
        load_images_path = ''
        if 'Loaded' in result:
            send = ''.join(result[1:]) + ' was created successfully.'

        return render(request, 'main/success_upload.html', {'result': send})

    return render(request, 'main/upload.html',)

# 게시글 목록
def post_list(request, class_code):
    page = request.GET.get('page', '1')

    classroom_list = ClassRoom.objects.order_by('-create_date').filter(class_code=class_code)
    paginator = Paginator(classroom_list, 10)

    print(class_code)

    page_obj = paginator.get_page(page)
    context = {'classroom_list': page_obj, 'class_code':class_code}
    return render(request, 'main/classroom_post_list.html', context)

# 수업 목록
def class_list(request):
    is_educator = False
    is_learner = False
    print(request.user.groups.all())
    for g in request.user.groups.all():
        if g.name == 'educator':
            is_educator = True
        if g.name == 'learner':
            is_learner = True
    
    if is_learner:
        attend_class_info = list()
        for c in Classes.objects.all():
            info = dict()
            if c.learners:
                if str(request.user) in c.learners:
                    #print(request.user,"는 ",c.class_name,"에 등록되어있습니다.")
                    # 교육자, 수업 이름, 현재 학습자 / 총 학습자
                    info['educator'] = str(c.educator)
                    info['class_name'] = str(c.class_name)
                    info['learners_num'] = str(c.learners_num)
                    info['max_learner'] = str(c.max_learner)
                    info['id'] = int(c.id)
                    info['code'] = int(c.code)
                if not info:
                    print("?")
                else:
                    attend_class_info.append(info)
                    #print(attend_class_info)
    elif is_educator:
        attend_class_info = list()
        for c in Classes.objects.all():
            info = dict()
            if str(c.educator) == str(request.user):
                #print(request.user,"는 ",c.class_name,"에 등록되어있습니다.")
                # 교육자, 수업 이름, 현재 학습자 / 총 학습자
                info['educator'] = str(c.educator)
                info['class_name'] = str(c.class_name)
                info['learners_num'] = str(c.learners_num)
                info['max_learner'] = str(c.max_learner)
                info['id'] = int(c.id)
                info['code'] = int(c.code)
            if not info:
                print("?")
            else:
                attend_class_info.append(info)
                #print(attend_class_info)

    context = {'attend_class_info': attend_class_info, 'is_educator': is_educator, 'is_learner': is_learner}
    return render(request, 'main/class_list.html', context)

# 모든 수업 확인(관리자용)
def class_list_all(request):
    page = request.GET.get('page', '1')
    class_list = Classes.objects.order_by('-create_date')
    paginator = Paginator(class_list, 10)

    page_obj = paginator.get_page(page)
    context = {'class_list': page_obj}
    return render(request, 'main/class_list_all.html', context)

# 수업 생성
@user_passes_test(educator_group_check, login_url='/main')
def class_create(request):
    if request.method == 'POST':
        # 중복되는 코드의 수업 존재 유무 체크
        r_code = request.POST['code']
        for c in Classes.objects.all():
            print("등록하려는 수업의 코드 : ", r_code)
            print("c의 수업 코드", c.code)
            if c.code == int(r_code):
                print("중복되는 코드의 수업이 이미 존재합니다.")
                return redirect('main:index')
        form = ClassesForm(request.POST)
        if form.is_valid():
            classes = form.save(commit=False)
            classes.educator = request.user # author 속성에 로그인 계정 저장
            classes.create_date = timezone.now()
            classes.save()
            return redirect('main:index')
    else:
        form = ClassesForm()
    context = {'form': form}
    return render(request, 'main/class_create.html', context)

# 수업 삭제
def class_delete(request, class_code):
    print("수업 삭제 구현중")
    print("수업 코드는 ",class_code)
    for c in ClassRoom.objects.all():
        print("이 게시물의 수업 코드는", c.class_code)
        if class_code == c.class_code:
            print("코드가 일치합니다. 해당 게시물을 삭제합니다.")
            classroom_delete(request, c.id)

    Class = get_object_or_404(Classes, code=class_code)
    Class.delete()
    return redirect('main:class_list')

# 수업 참가
def class_attend(request):
    if request.method == 'POST':
        r_code = request.POST['code']
        print("등록하려는 수업의 코드 : ", r_code)
        for c in Classes.objects.all():
            print(c,"의 코드는",c.code)
            if c.code == int(r_code):
                print("코드가 동일합니다.")
                l = c.learners
                if l:
                    c.learners = l + " " + str(request.user)
                else:
                    c.learners = str(request.user)
                c.learners_num = len(c.learners.split())
                c.save()
        return redirect('main:index')

    return render(request, 'main/class_attend.html')

# 메인 페이지
def index(request):
    return render(request, 'index.html')

# 수업 내용
def detail(request, classroom_id):
    classroom = get_object_or_404(ClassRoom, pk=classroom_id)
    #print("선택된 이미지 : ", classroom.docker_image)
    #print("이미지 개수 : ", classroom.container_cnt)
    links = classroom.links.split(',')
    print("컨테이너 주소 : ", links)
    print("게시글 코드 : ", classroom.class_code)
    
    is_educator = False
    is_learner = False
    
    for g in request.user.groups.all():
        if g.name == 'educator':
            is_educator = True
        if g.name == 'learner':
            is_learner = True
            
    for c in Classes.objects.all():
        if c.code == classroom.class_code:
            attend_learner = c.learners.split()
            learners_num = c.learners_num
            max_learners_num = c.max_learner
            # print(attend_learner)
            # print(learners_num)
            # print(max_learners_num)
    
    print(request.user.username)
    
    print(attend_learner)
    print(links)
    learners_links = dict()
    for _ in range(len(attend_learner)):
        learners_links[attend_learner[_]] = links[_]

    context = {'classroom': classroom, 'links':links, 'learners_links':learners_links}
    return render(request, 'main/classroom_detail.html', context)

# 컨테이너 생성
@user_passes_test(educator_group_check, login_url='/main')
def make_container(request, docker_image, container_cnt):
    f = open("main/port.txt", 'r')
    ports = deque(f.readline().split())
    f.close()

    links = ''
    for _ in range(int(container_cnt)):
        port = ports.popleft()
        cmd = 'docker run -d -p ' + port + ':80 ' + str(docker_image)
        result = os.popen(cmd)

        if _ == int(container_cnt)-1:
            links += 'http://168.188.123.173:'+port
        else:
            links += 'http://168.188.123.173:'+port+','
        print("생성된 컨테이너 : ", result.read())
    print(links)

    p = ''
    for _ in ports:
        p += _ + ' '

    print(p)

    f = open("main/port.txt", 'w')
    f.write(p)
    f.close()

    return links

# 수업 게시글 생성
@user_passes_test(educator_group_check, login_url='/main')
def classroom_create(request, class_code):
    image_list = images() # images 정보 가져오기


    for c in Classes.objects.all():
        if c.code == class_code:
            learners_num = c.learners_num

            if c.learners_num == 0:
                print("현재 수업에 학습자가 없습니다. 학습자의 참여 이후 수업을 게시하세요.")
                return redirect('main:post_list', class_code=class_code)
                
            attend_learner = c.learners.split()
            max_learners_num = c.max_learner
            print(attend_learner)
            print(learners_num)
            print(make_container)

    if request.method == 'POST':
        form = ClassRoomForm(request.POST)
        if form.is_valid():
            classroom = form.save(commit=False)
            classroom.author = request.user # author 속성에 로그인 계정 저장
            classroom.create_date = timezone.now()
            classroom.class_code = class_code

templates/main/class_attend.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">수업 등록</h5>
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="code" class="form-label">코드</label>
            <input type="number" class="form-control" name="code" id="code"
                value="0">
        </div>
        <input type="submit" value="수업 등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/main/class_create.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">수업 생성</h5>
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="class_name" class="form-label">수업 이름</label>
            <input type="text" class="form-control" name="class_name" id="class_name"
                value="{{ form.class_name.value | default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="max_learner" class="form-label">최대 학생 수</label>
            <div class="form-group">
                <select type="number" class="form-control" name="max_learner" id="max_learner">
                  <option>1</option>
                  <option>2</option>
                  <option>3</option>
                  <option>4</option>
                  <option>5</option>
                </select>
              </div>
        </div>
        <div class="mb-3">
            <label for="code" class="form-label">수업 코드</label>
            <input type="number" class="form-control" name="code" id="code"
                value="{{ form.code.value |default_if_none:'' }}">
        </div>
        <input type="submit" value="생성" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/main/class_list.html
{% extends 'base.html' %}
{% load main_filter %}
{% block content %}
<div class="container my-3">
  {% if is_learner %}
  <h1>참여한 수업</h1>
  <div style="display: flex; flex-direction: row; flex-wrap: wrap">
    {% for c in attend_class_info %}
    {#  Single Card Template:#}
    <div class="card" style="width: 18rem; margin: 10px">
      <a class="h2" href="{% url 'main:post_list' c.code %}">{{ c.class_name }}</a>
        <p>교육자 :{{ c.educator }}</p>
        <p>{{ c.learners_num }} / {{ c.max_learner }}</p>
    </div>
    {% endfor %}
  </div>
  {% endif %}
  {% if is_educator %}
  <h1>생성한 수업</h1>
  <div style="display: flex; flex-direction: row; flex-wrap: wrap">
    {% for c in attend_class_info %}
    {#  Single Card Template:#}
    <div class="card" style="margin: 8px">
      <a class="h2" style="margin: 8px; relative" href="{% url 'main:post_list' c.code %}">{{ c.class_name }}</a>
      <p style="margin: 8px;">교육자 : {{ c.educator }}</p>
      <p style="margin: 8px;">{{ c.learners_num }} / {{ c.max_learner }}</p>
    </div>
    {% endfor %}
  </div>
  {% endif%}

  {% if is_learner %}
  <a href="{% url 'main:class_attend' %}" class="btn btn-primary">수업 등록하기</a>
  {% endif %}
</div>
{% endblock %}

templates/main/classroom_attend.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">수업 등록</h5>
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="subject" class="form-label">코드</label>
            <input type="text" class="form-control" name="subject" id="subject"
                value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <input type="submit" value="수업 등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/main/classroom_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 수업 생성 -->
    <h2 class="border-bottom py-2">{{ classroom.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ classroom.content }}</div>
            <div class="d-flex justify-content-end">
                {% if classroom.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ classroom.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ classroom.author.username }}</div>
                    <div>{{ classroom.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                {% if request.user == classroom.author %}
                <a href="{% url 'main:classroom_modify' classroom.id %}" 
                    class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                    data-uri="{% url 'main:classroom_delete' classroom.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- 컨테이너 개수 만큼 버튼 생성 -->
    <div class="card my-3">
        <div class="card-body">
            <div class="mb-2">생성된 컨테이너</div>
            <div class="d-flex flex-column">
            {% for key, value in learners_links.items %}
                {% if key == request.user.username %}
                <a type="button" href={{ value }} class="btn btn-success">{{ value }}</a>
                {% endif %}
            {% endfor %}
            </div>
        </div>
    </div>
    <!-- 댓글 -->
    <h5 class="border-bottom my-3 py-2">{{classroom.comment_set.count}}개의 답변이 있습니다.</h5>
    {% for comment in classroom.comment_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ comment.content }}</div>
            <div class="d-flex justify-content-end">
                {% if comment.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ comment.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ comment.author.username }}</div>
                    <div>{{ comment.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                {% if request.user == comment.author %}
                <a href="{% url 'main:comment_modify' comment.id  %}" 
                    class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                    data-uri="{% url 'main:comment_delete' comment.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 댓글 등록 -->
    <form action="{% url 'main:comment_create' classroom.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock%}

templates/main/classroom_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">수업등록</h5>
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content" class="form-label">내용</label>
            <textarea type="text" class="form-control" name="content" id="content" rows="10"
                value="{{ form.content.value|default_if_none:'' }}"></textarea>
        </div>
        {% comment %} <div class="mb-3">
            <label for="container_cnt" class="form-label">컨테이너 개수</label>
            <div class="form-group">
                <select type="number" class="form-control" name="container_cnt" id="container_cnt">
                  <option>1</option>
                  <option>2</option>
                  <option>3</option>
                </select>
              </div>
        </div> {% endcomment %}
        <div class="my-3">
            <label for="container_cnt" class="form-label">이미지 목록</label>
            <select class="form-control" name="docker_image" id="docker_image" autofocus>
                {% for item in image_list %}
                    <option value="{{ item }}">{{ item }}</option>
                {% endfor %}
                </select>
        </div>
        <input type="submit" value="작성" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/main/classroom_post_list.html
{% extends 'base.html' %}
{% load main_filter %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="text-center table-dark">
                <th>번호</th>
                <th style="width:50%">제목</th>
                <th>글쓴이</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
        {% if classroom_list %}
        {% for classroom in classroom_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ classroom_list.paginator.count|sub:classroom_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-start">
                <a href="{% url 'main:detail' classroom.id %}">{{ classroom.subject }}</a>
                {% if classroom.comment_set.count > 0 %}
                <span class="text-danger small mx-2">{{ classroom.comment_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ classroom.author.username }}</td>
            <td>{{ classroom.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">수업이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if classroom_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ classroom_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in classroom_list.paginator.page_range %}
        {% if page_number >= classroom_list.number|add:-5 and page_number <= classroom_list.number|add:5 %}
        {% if page_number == classroom_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif%}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if classroom_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ classroom_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    {% for group in user.groups.all %}
    {% if group.name == 'educator' %}
    <a href="{% url 'main:classroom_create' class_code %}" class="btn btn-primary">게시글 등록</a>
    <a href="{% url 'main:class_delete' class_code %}" class="btn btn-danger ">수업 삭제</a>
    {% else %}
    {% endif %}
    {% endfor %}
</div>
{% endblock %}

templates/main/question_list.html
{% extends 'base.html' %}
{% load main_filter %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>
                <a href="{% url 'main:detail' question.id %}">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif%}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{% url 'main:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}