accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('class/class_list/', views.class_list, name='class_list'),
    path('class/class_list_all/', views.class_list_all, name='class_list_all'),
    path('class/class_create/', views.class_create, name='class_create'),
    path('class/class_delete/<int:class_code>', views.class_delete, name='class_delete'),
    path('class/class_attend/', views.class_attend, name='class_attend'),
    path('class/post_list/<int:class_code>', views.post_list, name='post_list'),
    path('<int:classroom_id>/', views.detail, name='detail'),
    path('comment/create/<int:classroom_id>/', views.comment_create, name='comment_create'),
    path('classroom/create/<int:class_code>', views.classroom_create, name='classroom_create'),
    path('classroom/modify/<int:classroom_id>/', views.classroom_modify, name='classroom_modify'),
    path('classroom/delete/<int:classroom_id>/', views.classroom_delete, name='classroom_delete'),
    path('comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path('upload/', views.upload, name='upload'),
]

security-education-web/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.index, name='index'), # '/'에 해당하는 path
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Security Class</title>
</head>
<body style="font-family: 'Tenada'">
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End-->
</body>
</html>

templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    {% for error in form.non_field_errors %}  <!-- 넌필드 오류를 출력한다. -->
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container mt-4 d-flex justify-content-center">
    <div class="row g-0">
        <div class="col-md-4 border-right">
            <div class="cards cards-custom">
                <div class="first bg-white px-1 py-5 text-center">
                    <img src="{% static 'img/man.png' %}" width="128" height="128">
                    <h5 class="h5-custom">User의 OS에 상관없이</h5>
                    <p class="line1">실습을 제공받아, 진행</p>
                </div>
            </div>
        </div>
        <div class="col-md-4 border-right">
            <div class="cards cards-custom">
                <div class="second bg-white px-1 py-5 text-center">
                    <img src="{% static 'img/group.png' %}" width="128" height="128">
                    <h5 class="h5-custom">교육자와 학습자</h5>
                    <p class="line1">하나의 실습 공간에서 수업을 진행</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="cards cards-custom">
                <div class="third bg-white px-1 py-5 text-center">
                    <img src="{% static 'img/docker.png' %}" width="128" height="128">
                    <h5 class="h5-custom">Docker를 통해 실습 제공</h5>
                    <p class="line1">Docker를 이용하여 학습자에게 실습을 제공</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/navbar.html
{% load static %}
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light border-bottom">
    <div class="container-sm">
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <a class="navbar-brand" href="{% url 'main:index' %}">
                SECURITYCLASS
            </a>
            <ul class="navbar-nav mx-auto">
                <!-- 교육자 - 수업 생성 -->
                {% for group in user.groups.all %}
                {% if group.name == 'educator' %}
                {% if user.is_authenticated %}
                <li>
                    <a class="nav-link" href="{% url 'main:class_create' %}">수업 생성</a>
                </li>
                {% endif %}
                {% else %}
                {% endif %}
                {% endfor %}
                <!-- 수업 목록 확인-->
                {% for group in user.groups.all %}
                {% if group.name == 'educator' or group.name == 'learner' %}
                <li>
                    <a class="nav-link" href="{% url 'main:class_list' %}">수업</a>
                </li>
                {% else %}
                {% endif %}
                {% endfor %}
                <!-- 모든 수업 목록 확인-->
                {% for group in user.groups.all %}
                {% if group.name == 'educator' %}
                {% if user.is_authenticated %}
                <li>
                    <a class="nav-link" href="{% url 'main:class_list_all' %}">모든 수업(교육자 용)</a>
                </li>
                {% endif %}
                {% else %}
                {% endif %}
                {% endfor %}
                <!-- docker 파일 업로드-->
                {% for group in user.groups.all %}
                {% if group.name == 'educator' %}
                {% if user.is_authenticated %}
                <li>
                    <a class="nav-link" href="{% url 'main:upload' %}">업로드</a>
                </li>
                {% endif %}
                {% else %}
                {% endif %}
                {% endfor %}
            </ul>
            <ul class="navbar-nav mb-0 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'accounts:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
        
    </div>
</nav>